version: "3"
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    restart: unless-stopped
    environment:
      - RABBITMQ_NODE_PORT_NUMBER=5672
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=1234
    ports:
      - 15672:15672
      - 5672:5672

  mongo:
    image: mongo:7.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  jaeger:
    image: jaegertracing/jaeger:2.4.0
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SECRET_KEY=helloABC
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
