version: "3"
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    restart: unless-stopped
    environment:
      - RABBITMQ_NODE_PORT_NUMBER=5672
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=1234
    ports:
      - 15672:15672
      - 5672:5672
      
  mongo:
    image: mongo:7.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
      
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
