version: "3"
services: 
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
      
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
